name: Run 'npm run lint'
on:
  push:
    branches-ignore:
      - master
      - main
  pull_request:
    branches:
      - '*'

jobs:
  unit_test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run linting
        run: npm run lint
        continue-on-error: false

      - name: Check linting errors
        run: |
          if [ ${{ job.status }} == 'failure' ]; then
            echo "Linting failed. Aborting the push."
            exit 1
          fi
