name: Run Unit Tests and Lint Files
on:
  push:
    branches:
      - main # Adjust the branch name as needed
  pull_request:
    branches:
      - main # Adjust the branch name as needed
jobs:
  unit_test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run:  npm install
      - run:  npm run lint
