name: Run 'npm run lint'
on: 'push'
jobs:
  unit_test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run:  npm install
      - run:  npm run lint
        continue-on-error: false 
